### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Emily-Steel** [Naviaux/osu-music-player#1]
When I try to launch the player with the following command : java "osu! Music Playerv1.3.6.jar"

Error: Could not find or load main class osu! Music Playerv1.3.6.jar

Am I missing something ?

**Comment by Naviaux** [comment]
Since it is a .jar file you should be able to simply double-click the file to run it. If that is not an option for you, trying using the -jar parameter in the Java command (it goes before the file name).

If that does not work than I shall look into other options for you.

**Comment by Emily-Steel** [comment]
I tried double-clicking first but it complained about an exception so I wanted to launch it from a terminal to see the output, thanks for the -jar parameter, sorry I didn't take the single minute I should've to find that info.

With -jar parameter it outputs the following :

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/arcing/naviaux/music/Launcher : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

My Java version :
java version "1.7.0_75"
Java(TM) SE Runtime Environment (build 1.7.0_75-b13)
Java HotSpot(TM) Client VM (build 24.75-b04, mixed mode, sharing)

I'm using Windows 8.1

**Comment by Naviaux** [comment]
As the program requires Java 8 to run l, having Java 7 (which is what you have installed) or any prior versions would cause the program to not run correctly.

Please update to Java 8 and let me know if you have any further issues.

Happy Streaming!

**Comment by Emily-Steel** [comment]
It works with Java 8 :) Thanks a lot for this brilliant player !

**Comment by Naviaux** [comment]
You are quite welcome! I hope you enjoy!
Feel free to post any more issues you come across.
